apiVersion: v1
kind: Pod
metadata: 
  name: example-pod
spec:
  containers:
  - name: example-container
    image: nginx

    resources:
      requests:
        cpu: 4
        memory: 6Gi
      limits:
        cpu: 6
        memory: 8Gi
  nodeSelector:
    project: x
    team: Dev