apiVersion: v1
kind: Pod
metadata: 
  name: example-pod-idside
spec:
  containers: 
  - name: example-container-idside
    image: nginx
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1  
        preference:
          matchExpressions:
          - key: diskType
            operator: In
            values:
            - ssd