apiVersion: v1
kind: Pod
metadata: 
  name: example-pod-idside-weight
spec:
  containers: 
  - name: example-container-idside-weight
    image: nginx
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1  
        preference:
          matchExpressions:
          - key: topology.kubernetes.io/zone
            operator: In
            values:
            - us-east-2c
      - weight: 1  
        preference:
          matchExpressions:
          - key: topology.kubernetes.io/zone
            operator: In
            values:
            - us-east-2a