apiVersion: v1
kind: Pod
metadata: 
  name: example-pod-rdside
spec:
  containers: 
  - name: example-container-rdside
    image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: diskType
            operator: In
            values:
            - ssd