apiVersion: v1
kind: Pod
metadata: 
  name: example-pod-rdside-1
spec:
  containers: 
  - name: example-container-rdside-1
    image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/zone
            operator: In
            values:
            - us-east-2c